### ISSUE TITLE
Let's Encrypt - Free Certificates

### ISSUE THREAD

**Issue by ellakdev** [OBI-GRIPO/e-filing#1]
For SSL Certificates please use  https://letsencrypt.org/

**Comment by sl45sms** [comment]
We use letsencrypt since commit https://github.com/OBI-GRIPO/e-filing/commit/2dd8c7983393ccf94cd6c504ea14ce7c7ac5dbea at 5 jul 2018 (the day that dns for site have been available for public). The site uses the Let's Encrypt staging server due  [rate limits](https://letsencrypt.org/docs/rate-limits/) of Let's Encrypt that can easyly are overcome due developmet. Once the development is over,  we switch to production.
